global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["localhost:8080"]
