name: Deploy to VPS

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          VPS_HOST: "46.202.132.119"
          VPS_USER: "root"
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            echo "Starting deployment..."
            if [ ! -d "/root/the-tip-top-app" ]; then
              echo "Directory not found, creating and cloning..."
              mkdir -p /root/the-tip-top-app
              cd /root/the-tip-top-app
              git clone https://github.com/CapitaineCro4/the-tip-top.git .
            else
              cd /root/the-tip-top-app
            fi
            git pull origin main || { echo "Git pull failed"; exit 1; }
            # Supprime les conteneurs existants pour éviter les conflits
            docker rm -f pushgateway prometheus grafana postgres_db api front backup || true
            docker-compose down || { echo "Docker-compose down failed"; exit 1; }
            docker-compose up --build -d || { echo "Docker-compose up failed"; exit 1; }
            echo "Deployment finished!"
          EOF