name: CI/CD Pipeline with Backup and Deploy

on:
  push:
    branches:
      - develop
      - preprod
      - main
  pull_request:
    branches:
      - develop
      - preprod
      - main
  schedule:
    - cron: "0 0 * * *" # Tous les jours à minuit UTC
    - cron: "0 0 * * 0" # Tous les dimanches à minuit UTC (hebdomadaire)
  workflow_dispatch: # Permet de déclencher manuellement si besoin

# Définition des permissions
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Job pour la CI (build, tests, optimisation)
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configuration Node.js pour le Front
      - name: Setup Node.js for Front
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: front/yarn.lock

      # Installation des dépendances Front
      - name: Install Front Dependencies
        working-directory: ./front
        run: |
          yarn install --frozen-lockfile
          yarn add -D prettier terser-webpack-plugin optimize-css-assets-webpack-plugin

      # Optimisation des assets Front (minification/compression)
      - name: Optimize Front Assets
        working-directory: ./front
        run: |
          yarn build

      # Configuration Node.js pour l'API
      - name: Setup Node.js for API
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: api/yarn.lock

      # Installation des dépendances API
      - name: Install API Dependencies
        working-directory: ./api
        run: |
          yarn install --frozen-lockfile
          yarn add -D prettier @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint jest @types/jest ts-jest supertest @types/supertest

      # Vérification du formatage et linting Front
      - name: Check Front Format and Lint
        working-directory: ./front
        run: |
          yarn format
          yarn lint
          yarn format:check

      # Vérification du formatage et linting API
      - name: Check API Format and Lint
        working-directory: ./api
        run: |
          yarn format
          yarn lint
          yarn format:check

      # Tests e2e pour API
      - name: Run API e2e Tests
        working-directory: ./api
        run: |
          yarn test:e2e
        env:
          NODE_ENV: test

      # Tests unitaires pour Front
      - name: Run Front Unit Tests
        working-directory: ./front
        run: |
          yarn test --coverage
        env:
          NODE_ENV: test

      # Stocker les rapports de tests
      - name: Store Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            ./api/coverage/
            ./front/coverage/
            ./api/test-results.json
            ./front/test-results.json

      # Installer Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      # Installer Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Créer un fichier .env
      - name: Create env file
        run: |
          echo "API_PORT=3002" >> .env
          echo "DATABASE_URL=postgresql://admin:admin@postgres_db:5432/mydatabase?schema=public" >> .env
          echo "JWT_SECRET=secret" >> .env
          echo "FRONT_PORT=3000" >> .env
          echo "NEXT_PUBLIC_API_URL=http://dsp5-archi-f24a-15m-g4.fr/api" >> .env

      # Build et push des images Docker
      - name: Build and Push API Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/the-tip-top-api:latest ./api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/the-tip-top-api:latest

      - name: Build and Push Front Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/the-tip-top-front:latest ./front
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/the-tip-top-front:latest

  # Job pour le déploiement
  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/develop'
        env:
          VPS_HOST: "46.202.132.119"
          VPS_USER: "root"
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
              echo "Deploying to dev..."
              cd /root/the-tip-top-app
              git fetch origin develop
              git reset --hard origin/develop || { echo "Git reset failed"; exit 1; }
              docker rm -f pushgateway prometheus grafana postgres_db api front backup || true
              docker-compose down || { echo "Docker-compose down failed"; exit 1; }
              docker-compose up --build -d || { echo "Docker-compose up failed"; exit 1; }
              echo "Deployment to dev finished!"
          EOF

      - name: Deploy to Preprod
        if: github.ref == 'refs/heads/preprod'
        env:
          VPS_HOST: "46.202.132.119"
          VPS_USER: "root"
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            echo "Deploying to preprod..."
            cd /root/the-tip-top-app
            git pull origin preprod || { echo "Git pull failed"; exit 1; }
            docker rm -f pushgateway prometheus grafana postgres_db api front backup || true
            docker-compose down || { echo "Docker-compose down failed"; exit 1; }
            docker-compose up --build -d || { echo "Docker-compose up failed"; exit 1; }
            echo "Deployment to preprod finished!"
          EOF

  deploy-production:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: http://dsp5-archi-f24a-15m-g4.fr
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Request manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: CapitaineCro4
          minimum-approvals: 1
          issue-title: "Manual approval required for production deployment"
          issue-body: "Please approve to deploy to production."

      - name: Deploy to Production
        if: success()
        env:
          VPS_HOST: "46.202.132.119"
          VPS_USER: "root"
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            echo "Deploying to production..."
            cd /root/the-tip-top-app
            git pull origin main || { echo "Git pull failed"; exit 1; }
            docker rm -f pushgateway prometheus grafana postgres_db api front backup || true
            docker-compose down || { echo "Docker-compose down failed"; exit 1; }
            docker-compose up --build -d || { echo "Docker-compose up failed"; exit 1; }
            echo "Deployment to production finished!"
          EOF

  # Job pour la publication des rapports de test
  pages:
    needs: ci
    runs-on: ubuntu-latest
    environment:
      name: Coverage test visualization page
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Download test reports
        uses: actions/download-artifact@v4
        with:
          name: test-reports
          path: coverage-reports

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "coverage-reports/front/coverage/lcov-report"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Job pour la sauvegarde automatique vers Google Drive
  backup:
    runs-on: ubuntu-latest
    needs: ci
    environment:
      name: backup
      url: https://drive.google.com # URL générique pour l'environnement, ajustez si nécessaire

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Google Drive API client
        run: |
          pip install google-auth-httplib2 google-auth-oauthlib google-api-python-client

      - name: Create backup archive
        run: |
          # Crée une archive des fichiers à sauvegarder
          tar -czf backup-$(date +%Y%m%d-%H%M%S).tar.gz .

      - name: Upload backup to Google Drive
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          FOLDER_ID: "1YOHfU8s4J2wy5Wl1-d_jYY9wZs_-eqoO" # Remplacez par l'ID du dossier Google Drive
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          python -c "
          from google.oauth2.service_account import Credentials
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaFileUpload
          import os

          creds = Credentials.from_service_account_file('credentials.json')
          drive_service = build('drive', 'v3', credentials=creds)

          file_metadata = {'name': 'backup-$(date +%Y%m%d-%H%M%S).tar.gz', 'parents': ['$FOLDER_ID']}
          media = MediaFileUpload('backup-$(date +%Y%m%d-%H%M%S).tar.gz')
          file = drive_service.files().create(body=file_metadata, media_body=media, fields='id').execute()
          print(f'File ID: {file.get(\"id\")}')
          "

      - name: Clean up
        if: always()
        run: |
          rm -f credentials.json backup-*.tar.gz
